### PR TITLE
Revove textures code

### PR DESCRIPTION
**Pull request by IagoLast**
Since textured markers are buggy in tangram, it makes no sense to have code for that in our
library.

Note: This PR needs to be used with a new version of the tangram-reference where marker-files are not allowed.

### CODE REVIEW

**Comment by IagoLast** [comment]
The use case would be:

1. Remove marker.file from the tangram reference 
2. Use the master branch against that reference
3. Load a map with markers
4. An error should be thrown.
5. With this branch the error disappears.

**Comment by alonsogarciapablo** [comment]
> 3. Load a map with markers

I guess the layer needs to have a `marker-file` in the CartoCSS, right?

**Comment by IagoLast** [comment]
Nope, In cartocss is called`url(..)`

**Comment by alonsogarciapablo** [comment]
It should have something like:

```
marker-file: url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/cafe-18.svg'
```

**Comment by IagoLast** [comment]
Right something like this:
``` 
#layer {
  marker-width: 20;
  marker-fill: #FFB927;
  marker-fill-opacity: 0.9;
  marker-file: url('https://s3.amazonaws.com/com.cartodb.users-assets.production/maki-icons/marker-18.svg');
  marker-allow-overlap: true;
  marker-line-width: 1;
  marker-line-color: #FFF;
  marker-line-opacity: 1;
}
```

**Comment by alonsogarciapablo** [comment]
I still see the following error in this branch:

```
renderer_js.js?5c39:245 Uncaught (in promise) Error: :5:2 Unrecognized rule: marker-file. Did you mean marker-fill?
    at CartoCSS.parse (renderer_js.js?5c39:245)
    at CartoCSS.setStyle (renderer_js.js?5c39:120)
    at CartoCSS (renderer_js.js?5c39:10)
    at carto.RendererJS.render (renderer_js.js?5c39:292)
    at Object.extractFeatures [as carto2Draw] (carto.js?81a1:16)
    at Object.TH.setLayerDraw (tangram-helper.js?a135:23)
    at eval (main.js?a292:52)
    at Array.forEach (<anonymous>)
    at _callee$ (main.js?a292:41)
    at tryCatch (runtime.js?1aab:65)
```

I guess that's the error that will be captured [here](https://github.com/CartoDB/tangram.cartodb/blob/master/src/tangram.js#L28-L31), right? I guess it's a legit error since this library doesn't support `marker-file`...

**Comment by IagoLast** [comment]
Since the new version of the carto compiler detects the error before reaching the tangram-carto code this I think PR is outdated

**Comment by alonsogarciapablo** [comment]
Closing this PR then.

**Pull request merged**
