### PR TITLE
Add Carto library

### PR DESCRIPTION
**Pull request by donflopez**
This PR remove my cartocss parser to use [the original well tested carto parser](https://github.com/CartoDB/carto).

### CODE REVIEW

**Comment by donflopez** [comment]
This PR fix #5

**Comment by javisantana** [comment]
nice, could you add some tests and add this to travis (or other ci) to be sure we are on track?

**Comment by javisantana** [comment]
in torque we use travis https://travis-ci.org/CartoDB/torque

**Comment by donflopez** [comment]
Sure! Let's do it :)

**Comment by donflopez** [comment]
I've added some tests, I'll test each function of the project, but this is a first step @javisantana

**Comment by javisantana** [comment]
nice, thanks :es:

**Pull request merged**
